/**
 * Paste the exact embed snippet generated by Tripadvisor's own Widget Center
 * (https://www.tripadvisor.com/Widgets) for this business's real Location ID —
 * including its <script> tag, verbatim. Use their "Review" widget type so it shows
 * individual review content (not just the rating summary, which is already handled
 * separately as a static owner-confirmed card). Spec §18/§48: never hand-construct
 * this markup or scrape Tripadvisor; only Tripadvisor's own generator for the real
 * listing produces a correct, safe snippet.
 *
 * Leave this empty to keep the Tripadvisor reviews block hidden on the Home page.
 */
export const TRIPADVISOR_WIDGET_EMBED_HTML = '';
